# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 521, 181))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(220, 240, 101, 31))
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 280, 541, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(560, 10, 201, 31))
        self.lblTtitulo.setStyleSheet("color:rgb(135, 0, 202);\n"
"font: 700 italic 9pt \"Times New Roman\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"")
        self.lblTtitulo.setObjectName("lblTtitulo")
        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(200, 0, 161, 51))
        self.lblTtitulo_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"border-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"\n"
"color:rgb(85, 0, 255)")
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")
        self.lblTtitulo2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo2.setGeometry(QtCore.QRect(10, 280, 171, 61))
        self.lblTtitulo2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo2.setText("")
        self.lblTtitulo2.setPixmap(QtGui.QPixmap("logo_eafit_blanco.png"))
        self.lblTtitulo2.setObjectName("lblTtitulo2")
        self.btnCalcularTrayectoriasK2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcularTrayectoriasK2.setGeometry(QtCore.QRect(570, 360, 201, 29))
        self.btnCalcularTrayectoriasK2.setObjectName("btnCalcularTrayectoriasK2")
        self.tableTrayectorias3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableTrayectorias3.setGeometry(QtCore.QRect(780, 510, 521, 181))
        self.tableTrayectorias3.setToolTip("")
        self.tableTrayectorias3.setRowCount(4)
        self.tableTrayectorias3.setColumnCount(4)
        self.tableTrayectorias3.setObjectName("tableTrayectorias3")
        self.btnCalcularTrayectoriasK3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcularTrayectoriasK3.setGeometry(QtCore.QRect(570, 590, 201, 29))
        self.btnCalcularTrayectoriasK3.setObjectName("btnCalcularTrayectoriasK3")
        self.lblTtitulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_2.setGeometry(QtCore.QRect(910, 10, 301, 31))
        self.lblTtitulo_2.setStyleSheet("color:rgb(170, 85, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"")
        self.lblTtitulo_2.setObjectName("lblTtitulo_2")
        self.tableAdyacencia = QtWidgets.QTableWidget(self.centralwidget)
        self.tableAdyacencia.setGeometry(QtCore.QRect(770, 40, 521, 181))
        self.tableAdyacencia.setToolTip("")
        self.tableAdyacencia.setRowCount(4)
        self.tableAdyacencia.setColumnCount(4)
        self.tableAdyacencia.setObjectName("tableAdyacencia")
        self.tableTrayectorias2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableTrayectorias2.setGeometry(QtCore.QRect(780, 280, 521, 181))
        self.tableTrayectorias2.setToolTip("")
        self.tableTrayectorias2.setRowCount(4)
        self.tableTrayectorias2.setColumnCount(4)
        self.tableTrayectorias2.setObjectName("tableTrayectorias2")
        self.lblTtitulo_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_4.setGeometry(QtCore.QRect(910, 240, 301, 31))
        self.lblTtitulo_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(170, 170, 255)")
        self.lblTtitulo_4.setObjectName("lblTtitulo_4")
        self.lblTtitulo_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_5.setGeometry(QtCore.QRect(910, 470, 301, 31))
        self.lblTtitulo_5.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(170, 170, 255)")
        self.lblTtitulo_5.setObjectName("lblTtitulo_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1307, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Haga doble clic en el cabezado de un vértice para generar una matriz de pesos"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.lblTtitulo.setText(_translate("MainWindow", "Grafos por Isa y JJ"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos"))
        self.btnCalcularTrayectoriasK2.setToolTip(_translate("MainWindow", "Haga click para calular las trayectorias cuando K=2"))
        self.btnCalcularTrayectoriasK2.setText(_translate("MainWindow", "Calcular Trayectorias K=2"))
        self.btnCalcularTrayectoriasK3.setToolTip(_translate("MainWindow", "Haga click para calcular las trayectorias cuando K=3"))
        self.btnCalcularTrayectoriasK3.setText(_translate("MainWindow", "Calcular Trayectorias K=3"))
        self.lblTtitulo_2.setText(_translate("MainWindow", "Matriz de Adyacencia"))
        self.lblTtitulo_4.setText(_translate("MainWindow", "Matriz de trayectorias K2"))
        self.lblTtitulo_5.setText(_translate("MainWindow", "Matriz de trayectorias K3"))